import { ArrowRight, Check, MoveUpRight } from 'lucide-react'

export function LandingPage({ onSignIn, onRegister }: { onSignIn: () => void; onRegister: () => void }) {
    return <main className="min-h-screen overflow-hidden bg-[#f5f7f5] text-[#24323a]">
        <nav className="flex items-center justify-between border-b border-[#dfe7e1] px-6 py-5 sm:px-10 lg:px-16">
            <div><p className="font-display text-2xl font-bold text-[#286f50]">VSR Forge</p><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#81968a]">Project intelligence</p></div>
            <div className="flex items-center gap-4"><button onClick={onSignIn} className="text-sm font-bold text-[#435159] hover:text-[#286f50]">Sign in</button><button onClick={onRegister} className="flex items-center gap-2 rounded-md bg-[#286f50] px-4 py-2.5 text-xs font-bold text-white hover:bg-[#1c6042]">Start building <ArrowRight size={15} /></button></div>
        </nav>
        <section className="grid min-h-[calc(100vh-84px)] items-center gap-12 px-6 py-14 sm:px-10 lg:grid-cols-[1.05fr_0.95fr] lg:gap-20 lg:px-16 lg:py-20">
            <div className="max-w-3xl"><p className="mb-6 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.2em] text-[#6d8878]"><span className="h-px w-10 bg-[#286f50]" /> The operating system for focused teams</p><h1 className="font-display text-6xl font-bold leading-[0.94] tracking-tight text-[#24323a] sm:text-7xl lg:text-8xl">Turn moving parts into <span className="text-[#286f50]">momentum.</span></h1><p className="mt-8 max-w-xl text-base leading-8 text-[#68767a] sm:text-lg">VSR Forge is a modern project workspace for teams who want clarity without the noise. Plan the work, track every issue, and make progress impossible to miss.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><button onClick={onRegister} className="flex items-center justify-center gap-2 rounded-md bg-[#286f50] px-6 py-4 text-sm font-bold text-white shadow-lg shadow-[#286f50]/20 hover:bg-[#1c6042]">Create your workspace <ArrowRight size={17} /></button><button onClick={onSignIn} className="flex items-center justify-center gap-2 rounded-md border border-[#b9cfc1] px-6 py-4 text-sm font-bold text-[#286f50] hover:bg-[#e8f1eb]">I already have an account</button></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-xs font-semibold text-[#81908b]"><span className="flex items-center gap-2"><Check size={15} className="text-[#286f50]" /> Issue management</span><span className="flex items-center gap-2"><Check size={15} className="text-[#286f50]" /> Team visibility</span><span className="flex items-center gap-2"><Check size={15} className="text-[#286f50]" /> Project momentum</span></div></div>
            <div className="relative min-h-[430px] border-l border-[#d6e2d9] pl-8 sm:pl-14 lg:min-h-[520px]"><div className="absolute left-0 top-0 h-20 w-px bg-[#286f50]" /><div className="flex h-full flex-col justify-between"><div><p className="font-display text-8xl font-bold leading-none text-[#dce9df] sm:text-[10rem]">01</p><p className="mt-3 text-xs font-bold uppercase tracking-[0.18em] text-[#6d8878]">One clear view</p></div><div className="border-t border-[#d6e2d9] pt-6"><p className="max-w-sm font-display text-3xl leading-tight text-[#24323a]">From first idea to final delivery, your team always knows what matters next.</p><button onClick={onRegister} className="mt-6 flex items-center gap-2 text-sm font-bold text-[#286f50]">Explore the workspace <MoveUpRight size={16} /></button></div><div className="grid grid-cols-3 gap-4 border-t border-[#d6e2d9] pt-6 text-xs"><div><p className="font-display text-2xl font-bold text-[#24323a]">01</p><p className="mt-1 text-[#81908b]">Shared source of truth</p></div><div><p className="font-display text-2xl font-bold text-[#24323a]">∞</p><p className="mt-1 text-[#81908b]">Room to grow</p></div><div><p className="font-display text-2xl font-bold text-[#24323a]">24/7</p><p className="mt-1 text-[#81908b]">Team visibility</p></div></div></div></div>
        </section>
        <section className="border-t border-[#dfe7e1] bg-[#286f50] px-6 py-16 text-white sm:px-10 lg:px-16 lg:py-20"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#c8dfd0]">Built for the whole journey</p><h2 className="mt-3 max-w-md font-display text-4xl leading-tight sm:text-5xl">Less chasing. More making.</h2></div><div className="grid gap-8 sm:grid-cols-3"><div className="border-t border-[#73a58b] pt-4"><p className="font-display text-2xl">01</p><h3 className="mt-3 text-sm font-bold">Align the work</h3><p className="mt-2 text-sm leading-6 text-[#d5e8dc]">Turn goals into visible projects, priorities, and next steps.</p></div><div className="border-t border-[#73a58b] pt-4"><p className="font-display text-2xl">02</p><h3 className="mt-3 text-sm font-bold">Move with confidence</h3><p className="mt-2 text-sm leading-6 text-[#d5e8dc]">Keep every issue’s owner, status, and urgency in one place.</p></div><div className="border-t border-[#73a58b] pt-4"><p className="font-display text-2xl">03</p><h3 className="mt-3 text-sm font-bold">See what is next</h3><p className="mt-2 text-sm leading-6 text-[#d5e8dc]">Give the team a shared view of progress without another meeting.</p></div></div></div></section>
        <section className="flex flex-col items-start justify-between gap-8 border-t border-[#dfe7e1] px-6 py-14 sm:flex-row sm:items-center sm:px-10 lg:px-16"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#6d8878]">Ready when you are</p><h2 className="mt-2 font-display text-3xl font-bold text-[#24323a]">Give your next project a clearer starting point.</h2></div><button onClick={onRegister} className="flex shrink-0 items-center gap-2 text-sm font-bold text-[#286f50]">Create your workspace <MoveUpRight size={17} /></button></section>
    </main>
}
