import { useState } from 'react'
import type { Issue, IssueType, Priority } from '../types'

export function CreateIssueModal({ onClose, onCreate }: { onClose: () => void; onCreate: (issue: Issue) => void }) {
  const [title, setTitle] = useState('')
  const [type, setType] = useState<IssueType>('Task')
  const [priority, setPriority] = useState<Priority>('Medium')
  const submit = () => { if (!title.trim()) return; onCreate({ id: `TASK-${Math.floor(Math.random() * 800 + 200)}`, title: title.trim(), type, priority, status: 'Todo', assignee: 'Vijay R.', initials: 'VR', tone: 'blue' }); onClose() }
  return <div className="fixed inset-0 z-10 grid place-items-center bg-[#27313b]/30 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><span className="text-[10px] font-bold uppercase tracking-[1.5px] text-[#7b8b87]">New work item</span><h2 className="mt-1 font-display text-2xl font-bold">Create issue</h2></div><button onClick={onClose} className="border-0 bg-transparent text-xl text-[#829097]" aria-label="Close">×</button></div><label className="mb-4 block text-xs font-bold text-[#68767c]">Title<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && submit()} className="mt-2 w-full rounded-md border border-[#e5e8e5] p-2.5 text-sm font-normal outline-none focus:border-[#39805f]" placeholder="What needs to be done?" /></label><div className="mb-5 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-[#68767c]">Type<select value={type} onChange={(event) => setType(event.target.value as IssueType)} className="mt-2 w-full rounded-md border border-[#e5e8e5] bg-white p-2.5 text-xs font-normal"><option>Task</option><option>Bug</option><option>Feature</option></select></label><label className="text-xs font-bold text-[#68767c]">Priority<select value={priority} onChange={(event) => setPriority(event.target.value as Priority)} className="mt-2 w-full rounded-md border border-[#e5e8e5] bg-white p-2.5 text-xs font-normal"><option>Medium</option><option>High</option><option>Urgent</option></select></label></div><div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-md border border-[#dce3df] bg-white px-4 py-2 text-xs font-bold text-[#68767c]">Cancel</button><button onClick={submit} disabled={!title.trim()} className="rounded-md bg-[#286f50] px-4 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Create issue</button></div></div></div>
}
