import { useState } from 'react'
import { Filter, Plus, Search } from 'lucide-react'
import { columns } from '../data'
import type { Issue } from '../types'
import { PanelTitle } from './Typography'
import { IssueCard } from './IssueCard'

export function IssueBoard({ issues, searchable = true, onOpenIssue, onArchiveIssue, onCreateIssue, onViewIssues }: { issues: Issue[]; searchable?: boolean; onOpenIssue: (issue: Issue) => void; onArchiveIssue: (issue: Issue) => void; onCreateIssue?: () => void; onViewIssues?: () => void }) {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All issues')
  const visible = issues.filter((issue) => `${issue.id} ${issue.title} ${issue.assignee}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All issues' || issue.type === filter))
  return <section className="rounded-[9px] border border-[#e5e8e5] bg-white p-4 sm:p-5"><div className="mb-5 flex items-center justify-between"><PanelTitle eyebrow="Team workload" title="Issue board" action={searchable ? 'Clear filters' : onViewIssues ? 'View all issues →' : undefined} onAction={searchable ? () => { setQuery(''); setFilter('All issues') } : onViewIssues} />{onCreateIssue && <button onClick={onCreateIssue} className="flex items-center gap-1 rounded-md bg-[#286f50] px-2.5 py-1.5 text-[10px] font-bold text-white"><Plus size={13} /> New</button>}</div>{searchable && <div className="mb-5 flex gap-2"><label className="flex h-9 flex-1 items-center gap-2 rounded-md border border-[#e5e8e5] px-2.5 text-[#9ca7ab]"><Search size={17} /><input className="w-full border-0 text-[11px] outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search issues..." /></label><label className="flex h-9 items-center gap-1.5 rounded-md border border-[#e5e8e5] px-2 text-[#66747a]"><Filter size={15} /><select className="border-0 bg-transparent text-[11px] outline-none" value={filter} onChange={(event) => setFilter(event.target.value)}><option>All issues</option><option>Bug</option><option>Feature</option><option>Task</option></select></label></div>}{visible.length === 0 && <p className="rounded-md bg-[#f5f7f5] p-4 text-xs text-[#76838a]">No matching issues. Try another search.</p>}<div className="grid grid-cols-5 gap-2.5 overflow-x-auto pb-1">{columns.map((column) => <div className="min-w-[130px]" key={column}><div className="mb-3 flex items-center gap-1.5 text-[10px] text-[#65737b]"><i className={`h-2 w-2 rounded-full ${column === 'In progress' ? 'bg-[#e79b5a]' : column === 'Code review' ? 'bg-[#8098bd]' : column === 'Testing' ? 'bg-[#b596cf]' : column === 'Done' ? 'bg-[#59a77d]' : 'bg-[#c8cfd1]'}`} /><strong>{column}</strong><span className="ml-auto text-[#aeb6b9]">{visible.filter((issue) => issue.status === column).length}</span></div>{visible.filter((issue) => issue.status === column).map((issue) => <IssueCard issue={issue} key={issue.id} onOpen={() => onOpenIssue(issue)} onArchive={() => onArchiveIssue(issue)} />)}</div>)}</div></section>
}
