import { Check, CircleDot, Clock3, ShieldCheck } from 'lucide-react'
import type { Issue } from '../types'
import { ActivityPanel } from '../components/ActivityPanel'
import { IssueBoard } from '../components/IssueBoard'
import { MetricCard } from '../components/MetricCard'
import { Eyebrow } from '../components/Typography'

export function OverviewPage({ issues, onOpenIssue, onArchiveIssue, onCreateIssue, onViewIssues }: { issues: Issue[]; onOpenIssue: (issue: Issue) => void; onArchiveIssue: (issue: Issue) => void; onCreateIssue: () => void; onViewIssues: () => void }) {
  return <><section className="mb-4 flex flex-col justify-between gap-5 rounded-[10px] border border-[#dcebe2] bg-gradient-to-r from-[#edf8f1] via-[#f8fbf8] to-[#eff7f3] p-6 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-[11px] bg-[#2d7554] text-xs font-bold text-white shadow-[inset_0_-4px_#16543b]">PC</div><div><Eyebrow>Active project</Eyebrow><h2 className="mt-1 font-display text-[22px] font-bold">Pulse Commerce</h2><p className="text-xs text-[#7d9287]">Building a faster, friendlier checkout experience.</p></div></div><div className="flex flex-wrap gap-6 text-xs text-[#435c50]"><div><span className="mb-1 block text-[10px] text-[#8b9b93]">Team</span><strong>8 members</strong></div><div><span className="mb-1 block text-[10px] text-[#8b9b93]">Target date</span><strong>Jun 28, 2024</strong></div><div className="w-32"><span className="mb-1 flex justify-between text-[10px] text-[#8b9b93]">Progress <b>68%</b></span><div className="h-1.5 overflow-hidden rounded bg-[#d5e6dc]"><i className="block h-full w-[68%] rounded bg-[#358860]" /></div></div></div></section><section className="mb-7 grid grid-cols-2 gap-3.5 lg:grid-cols-4"><MetricCard icon={<CircleDot />} label="Total issues" value="24" detail="+4 this week" positive /><MetricCard icon={<Clock3 />} label="In progress" value="8" detail="2 need attention" /><MetricCard icon={<Check />} label="Completed" value="16" detail="+12% from last week" positive /><MetricCard icon={<ShieldCheck />} label="On track" value="92%" detail="Healthy project" positive /></section><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_285px]"><IssueBoard issues={issues} onOpenIssue={onOpenIssue} onArchiveIssue={onArchiveIssue} onCreateIssue={onCreateIssue} onViewIssues={onViewIssues} /><ActivityPanel /></div></>
}
