import { useState } from 'react'
import { Check, Mail, ShieldCheck, UserRound } from 'lucide-react'
import type { User } from '../auth'
import { Avatar } from '../components/Avatar'

export function ProfilePage({ user, onSaved }: { user: User; onSaved: (user: User) => void }) {
  const [name, setName] = useState(user.name)
  const [email, setEmail] = useState(user.email)
  const initials = name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()

  return <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="border border-[#e5e8e5] bg-white p-6 sm:p-8"><div className="flex flex-col gap-5 border-b border-[#e5e8e5] pb-7 sm:flex-row sm:items-center"><Avatar initials={initials} tone="mint" /><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6d8878]">Your profile</p><h2 className="mt-1 font-display text-3xl font-bold text-[#24323a]">Account details</h2><p className="mt-1 text-sm text-[#8a969c]">Manage how your teammates see you in VSR Forge.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold text-[#435159]">Full name<div className="flex items-center gap-3 border border-[#dce4df] px-3 focus-within:border-[#286f50]"><UserRound size={16} className="text-[#8a969c]" /><input value={name} onChange={(event) => setName(event.target.value)} className="w-full bg-transparent py-3 text-sm font-normal outline-none" /></div></label><label className="grid gap-2 text-xs font-bold text-[#435159]">Email address<div className="flex items-center gap-3 border border-[#dce4df] px-3 focus-within:border-[#286f50]"><Mail size={16} className="text-[#8a969c]" /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full bg-transparent py-3 text-sm font-normal outline-none" /></div></label></div><button onClick={() => onSaved({ ...user, name: name.trim() || user.name, email: email.trim() || user.email })} className="mt-7 flex items-center gap-2 bg-[#286f50] px-5 py-3 text-xs font-bold text-white hover:bg-[#1c6042]"><Check size={15} /> Save profile</button></div><aside className="border border-[#e5e8e5] bg-[#eaf2ec] p-6"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#286f50]"><ShieldCheck size={16} /> Account status</p><p className="mt-5 font-display text-2xl font-bold text-[#24323a]">{user.role}</p><p className="mt-2 text-sm leading-6 text-[#68767a]">Your account is active and ready to collaborate across projects and issues.</p><div className="mt-6 border-t border-[#c9ddcf] pt-4 text-xs text-[#6d8878]"><p>Signed in as</p><p className="mt-1 font-bold text-[#435159]">{user.email}</p></div></aside></section>
}
